server:
  port: 9000
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
spring:
  config:
    import:
      - file:.env[.properties]
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  service:
    jwt:
      secret-key : ${JWT_SECRET_KEY}
      access-token-expiration: 43200000 # 12hrs
      refresh-token-expiration: 2592000000 # 30 days

springdoc:
  swagger-ui:
    operations-sorter: alpha

# logging
logging:
  level:
    com.test.oauth: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
    path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/db;AUTO_SERVER=TRUE;MODE=MySQL
    username: sa
    password: 178432
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_LOCAL_URI}
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_LOCAL_URI}
          naver:
            redirect-uri: ${NAVER_REDIRECT_LOCAL_URI}
  service:
    file:
      base-path: /Users/onhz/workspace/images/
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
#    url: jdbc:postgresql://on-hz-postgres:5432/onhz
    url: jdbc:postgresql://220.116.96.179:5432/onhz
    username: onhz
    password: onhz
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_DEV_URI}
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_DEV_URI}
          naver:
            redirect-uri: ${NAVER_REDIRECT_DEV_URI}
  service:
    file:
      base-path: /Users/onhz/workspace/images/