spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./data/db;AUTO_SERVER=TRUE;MODE=MySQL
    username: sa
    password: 178432
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_LOCAL_URI}
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_LOCAL_URI}
          naver:
            redirect-uri: ${NAVER_REDIRECT_LOCAL_URI}