spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/onhz
    username: onhz
    password: onhz
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_DEV_URI}
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_DEV_URI}
          naver:
            redirect-uri: ${NAVER_REDIRECT_DEV_URI}